#ifndef MOBILENETSSD_GLOBAL_H
#define MOBILENETSSD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOBILENETSSD_LIBRARY)
#  define MOBILENETSSDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOBILENETSSDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOBILENETSSD_GLOBAL_H
